-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bed1
(
    bed_id integer NOT NULL,
    bed_tier integer NOT NULL,
    CONSTRAINT bed_pkey PRIMARY KEY (bed_id)
);

CREATE TABLE IF NOT EXISTS public.booking1
(
    booking_id integer NOT NULL,
    bed_id integer NOT NULL,
    client_id integer NOT NULL,
    date_in date NOT NULL,
    date_out date NOT NULL,
    booking_price integer NOT NULL,
    CONSTRAINT bookingid_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.payment1
(
    payment_id integer NOT NULL,
    booking_id integer NOT NULL,
    method character varying(100) NOT NULL,
    CONSTRAINT payment_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.client
(
    client_id integer NOT NULL,
    client_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    client_pasport integer NOT NULL,
    client_phone integer NOT NULL,
    CONSTRAINT clientid_pkey PRIMARY KEY (client_id)
);

ALTER TABLE IF EXISTS public.bed1
    ADD FOREIGN KEY (bed_id)
    REFERENCES public.booking1 (bed_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payment1
    ADD FOREIGN KEY (booking_id)
    REFERENCES public.booking1 (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.client
    ADD FOREIGN KEY (client_id)
    REFERENCES public.booking1 (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;